version: "3"
services:
  bot:
    container_name: daruma-bot
    build: .
    restart: always
    volumes:
      - ./data:/data
      - ./logs:/logs
    environment:
      - ADMIN_CHANNEL_ID=${ADMIN_CHANNEL_ID}
      - BOT_OWNER_ID=${BOT_OWNER_ID}
      - BOT_TOKEN=${BOT_TOKEN}
      - CLAWBACK_TOKEN_MNEMONIC=${CLAWBACK_TOKEN_MNEMONIC}
      - SQLITE_DB_PATH=${SQLITE_DB_PATH}
      - TENOR_API_KEY=${TENOR_API_KEY}
      - TRANSACTION_WEBHOOK=${TRANSACTION_WEBHOOK}
      - WINSTON_LOGS_DIR=/logs
